Disallow insecure randomness functions
spaze/phpstan-disallowed-calls pull request #145
Opened 2022-12-03 01:26 UTC by compwright

2022-12-03 01:39 UTC, spaze requested changes
Thanks, this is a good idea! I'd only leave out the seeding functions, and please move the functions in the `disallowedFunctionCalls` section, you have it in methods.

2022-12-03 01:39 UTC, spaze commented on disallowed-insecure-calls.neon
> +			message: 'not cryptographically secure, use random_int() instead'
Although I see calling this function as a red flag, I'd leave this out, the function itself doesn't really do anything insecure.

2022-12-03 01:39 UTC, spaze commented on disallowed-insecure-calls.neon
> +			message: 'not cryptographically secure, use random_int() instead'
Same here

2022-12-05 15:33 UTC, spaze commented on disallowed-insecure-calls.neon
> +			message: 'not cryptographically secure, use random_int() instead'
Removed

2022-12-05 15:33 UTC, spaze commented on disallowed-insecure-calls.neon
> +			message: 'not cryptographically secure, use random_int() instead'
Removed

2022-12-05 15:36 UTC, spaze approved these changes

2022-12-05 15:36 UTC, merged

2022-12-05 15:36 UTC, spaze commented
Thank you! I've made some small changes:
- removed the seeding functions
- moved the new block of functions to the `disallowedFunctionCalls` section
- slightly changed the message
- added tests

and pushed the Merge button

2022-12-05 15:58 UTC, compwright commented
Thank you!

2022-12-06 12:54 UTC, compwright commented
Will there be a release soon?

2022-12-06 13:14 UTC, spaze commented
> Will there be a release soon?

Hopefully later today :-) I want to sneak in one more thing I'm working on now.

2022-12-07 03:51 UTC, spaze commented
Just released the updated config in [2.11.0](https://github.com/spaze/phpstan-disallowed-calls/releases/tag/v2.11.0), let me know if that's ok. Thanks for the contribution 👍