Use fnmatch for callMatches
spaze/phpstan-disallowed-calls pull request #53
Opened 2021-02-17 15:37 UTC by ruudk

I think it's good to always use `fnmatch` instead of doing strpos * trick.

2021-02-17 18:40 UTC, spaze commented
Please add an example of what benefits it brings, and tests. Thanks.

2021-02-18 07:10 UTC, ruudk commented
Rebased the PR. Please review this commit by commit as it explains what is done and why. 

If you accept this, you can squash merge it if that's what you want.

2021-02-18 22:23 UTC, spaze requested changes
I'm not sure this is useful but am fine merging it anyway. Though please keep the diff as small as possible.

2021-02-18 22:23 UTC, spaze commented on src/DisallowedHelper.php
> +			if ($this->matches($disallowedCall->getCall(), $name) && !$this->isAllowed($scope, $node, $disallowedCall)) {
No need to modify the line.

2021-02-19 08:16 UTC, ruudk commented on src/DisallowedHelper.php
> +			if ($this->matches($disallowedCall->getCall(), $name) && !$this->isAllowed($scope, $node, $disallowedCall)) {
Reverted.

2021-02-19 08:19 UTC, ruudk commented
@spaze Updated the PR, it's now ready ✅

2021-02-19 21:39 UTC, spaze approved these changes

2021-02-19 21:39 UTC, merged

2021-02-19 21:40 UTC, spaze commented
Awesome, thank you. Also thanks for the detailed commit descriptions, makes a reviewer's life much easier significantly increasing the chance it will get merged (soon, or at all) 👍

2021-02-19 22:41 UTC, spaze commented
Just released this in 1.3.0, thanks.