Allow specifying `identifier` to `RuleError`
spaze/phpstan-disallowed-calls pull request #97
Opened 2021-12-12 17:14 UTC by ruudk

Ultimately every error in PHPStan should have its own unique identifier so that its
possible to group by error type and ignore errors based on identifier.

https://github.com/phpstan/phpstan/issues/1686#issuecomment-532996159
https://github.com/phpstan/phpstan/issues/3065

2021-12-12 17:21 UTC, spaze commented
Oh nice, thanks! I always wanted to start using `RuleErrorBuilder` but never got around to it. I'll check the whole PR later.

2021-12-12 20:52 UTC, spaze requested changes
Thanks for the PR. Some smaller things I'd like (youl to address 😀 I've also merged the previous PR so you can rebase this one.

2021-12-12 20:52 UTC, spaze commented on src/DisallowedCall.php
> +		$this->identifier = (string) $identifier;
The method only accepts `string`, you can remove the typecast.

2021-12-12 20:52 UTC, spaze commented on src/DisallowedCall.php
> +	 * @return string
Can remove the doctype as the return type is in the method signature already.

2021-12-12 20:52 UTC, spaze commented on src/DisallowedConstant.php
> +	 * @return string
Same here, can drop the doctype.

2021-12-12 20:52 UTC, spaze commented on src/DisallowedNamespace.php
> +	 * @return string
And here as well, can remove the doctype :-)

2021-12-12 20:52 UTC, spaze commented on phpstan.neon
> +		ForbiddenCallsConfig: 'array<array{function?:string, method?:string, message?:string, allowIn?:string[], allowInFunctions?:string[], allowInMethods?:string[], allowParamsInAllowed?:array<integer, i
Thinking about the `identifier` keyword, seems too generic. Maybe "errorIdentifier"? "errorId"?

2021-12-12 20:52 UTC, spaze commented on phpstan.neon
> +		ForbiddenCallsConfig: 'array<array{function?:string, method?:string, message?:string, allowIn?:string[], allowInFunctions?:string[], allowInMethods?:string[], allowParamsInAllowed?:array<integer, i
Also please remove the space after `:` (yeah, I know 🤭)

2021-12-12 20:52 UTC, spaze commented on phpstan.neon
> +		ForbiddenCallsConfig: 'array<array{function?:string, method?:string, message?:string, allowIn?:string[], allowInFunctions?:string[], allowInMethods?:string[], allowParamsInAllowed?:array<integer, i
Also also, can you please add a line to README that would describe the config keyword (and make the support official and documented)?

2021-12-13 19:11 UTC, ruudk commented
@spaze I have no idea how to solve the phpcs issues. They conflict with each other. If I run `composer run cs-fix` it cannot fix it. What to do?

2021-12-14 00:26 UTC, spaze commented
> @spaze I have no idea how to solve the phpcs issues. They conflict with each other. If I run `composer run cs-fix` it cannot fix it. What to do?

Oh what a mess! :-D Couldn't hit the problem first but then I ran `composer update` and voila, shit. Seems that a [new code sniffer version](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.6.2) released just yesterday "Added new PSR12.Classes.OpeningBraceSpace sniff to enforce this" (https://github.com/squizlabs/PHP_CodeSniffer/issues/3437).

I'll update the coding style to remove the new requirement. Sorry for the trouble and thanks for hitting it before I do :-)

2021-12-14 00:49 UTC, spaze commented
@ruudk all green now again :-) As an extra I've also added PHP 8.1 tests and rebased this branch. Let me know once the PR is ready, I'll re-review or something. Currently sort of busy so please allow a day or 2 (or 5). Thanks!

2021-12-30 05:04 UTC, spaze commented on src/Usages/ClassConstantUsages.php
> +					))->build(),
Note to self: no need for `->identifier(...)` here because the error is not a *disallowed call* error.

2021-12-30 05:05 UTC, merged